# Generated by Django 3.2.8 on 2021-10-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfav', '0002_auto_20211026_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfav',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
